Make e2e-tests main application repo
PerfectFit-project/virtual-coach-main pull request #9
Opened 2021-12-30 10:25 UTC by svenvanderburg

2021-12-30 10:25 UTC, svenvanderburg commented on .gitignore
> -_test_dir
Renamed it to 'build', which is already in .gitignore

2022-01-03 13:31 UTC, dsmits requested changes
Looks good! Just a couple of very small remarks

2022-01-03 13:31 UTC, dsmits commented on script/fetch_and_build_all_images.sh
I would add a shebang to this script that indicates that this should be run using bash:
```suggestion
#!/bin/bash
```

2022-01-03 13:31 UTC, dsmits commented on script/server
> +bash fetch_and_build_all_images.sh
If you add the shebang to the `fetch_and_build_all_images.sh` script and make it executable you don't have to call it here with bash. I would prefer to do it like this then:
```suggestion
./fetch_and_build_all_images.sh
```

2022-01-03 14:50 UTC, svenvanderburg commented
Nice suggestions :)

2022-01-03 14:50 UTC, merged